# Generated by Django 4.1.2 on 2023-05-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=155, null=True),
        ),
    ]
